<a href="https://colab.research.google.com/github/RitwikRocks/Machine-Learning/blob/main/AllRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Testing the Best Regression for our dataset

# Importing the Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importng the Dataset

In [8]:
dataset = pd.read_csv("Data.csv")
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


# Spliting the data in Training and Testing set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)


# Multiple Linear Regression

In [5]:
from sklearn.linear_model import LinearRegression
reg1 = LinearRegression()
reg1.fit(X_train,Y_train)

LinearRegression()

In [27]:
y_mul = reg1.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_mul.reshape(len(y_mul),1),Y_test.reshape(len(Y_test),1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


# Polynomial Linear Regression

In [41]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X_train)
reg2 = LinearRegression()
reg2.fit(X_poly,Y_train)


LinearRegression()

In [42]:
y_poly = reg2.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_poly.reshape(len(y_poly),1),Y_test.reshape(len(Y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


# Decision Tree Regression

In [43]:
from sklearn.tree import DecisionTreeRegressor
reg3 = DecisionTreeRegressor(random_state=0)
reg3.fit(X_train,Y_train)

DecisionTreeRegressor(random_state=0)

In [44]:
y_dtree = reg3.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_dtree.reshape(len(y_dtree),1),Y_test.reshape(len(Y_test),1)),1))

[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]


# Random Forest Regression

In [45]:
from sklearn.ensemble import RandomForestRegressor
reg4 = RandomForestRegressor(n_estimators=10,random_state=0)
reg4.fit(X_train,Y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [46]:
y_forest = reg4.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_forest.reshape(len(y_forest),1),Y_test.reshape(len(Y_test),1)),1))

[[434.05 431.23]
 [458.79 460.01]
 [463.02 461.14]
 ...
 [469.48 473.26]
 [439.57 438.  ]
 [460.38 463.28]]


# Support Vector Regression

# Feature Scaling

In [56]:
y1 = Y.reshape(len(Y),1)
X1_train,X1_test,Y1_train,Y1_test = train_test_split(X,y1,test_size=0.2,random_state=0)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [62]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_Y = StandardScaler()
X1_train = sc_X.fit_transform(X1_train)
Y1_train = sc_Y.fit_transform(Y1_train)


[[473.93]
 [467.87]
 [431.97]
 ...
 [459.01]
 [462.72]
 [428.12]]


In [53]:
from sklearn.svm import SVR
reg5 = SVR(kernel="rbf")
reg5.fit(X1_train,Y1_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [65]:
y_svr = (reg5.predict(sc_X.transform(X1_test)).reshape(-1,1))
y_svr = sc_Y.inverse_transform(y_svr)
np.set_printoptions(precision=2)
print(np.concatenate((y_svr.reshape(len(y_svr),1),Y1_test.reshape(len(Y_test),1)),1))

[[434.05 431.23]
 [457.93 460.01]
 [461.02 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


# Testing which is the Best among all thje Models for this Dataset
for this we use a method called R-squared Error method
R squared = 1 - SSreg/SSavg
SSrg = reg curve slope value
SSavg = avg curve slope value
if 1 = perfect fit (suspecious)

  more than  0.9 = very good

  less than 0.7 = not good

  less than 0.4 = Terrible

  less than 0 model makes no sense

In [66]:
from sklearn.metrics import r2_score
r2_mul = r2_score(y_mul,Y_test)
r2_poly = r2_score(y_poly,Y_test)
r2_dtree = r2_score(y_dtree,Y_test)
r2_forest = r2_score(y_forest,Y_test)
r2_svr = r2_score(y_svr,Y_test)

# The Result

In [69]:
print(f"The R squared values for different predictions are : ")
print(f"Multiple Linear Regression :         {r2_mul}\n")
print(f"Polynomial Linear Regression :       {r2_poly}\n")
print(f"Decision Tree Regression :           {r2_dtree}\n")
print(f"Random Forest Regression :           {r2_forest}\n")
print(f"Support Vector Regression :          {r2_svr}")


The R squared values for different predictions are : 
Multiple Linear Regression :         0.9277905636321646

Polynomial Linear Regression :       0.942511209275948

Decision Tree Regression :           0.9217754458097261

Random Forest Regression :           0.9599399648940179

Support Vector Regression :          0.9462302628215628
