<a href="https://colab.research.google.com/github/RitwikRocks/Machine-Learning/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression
It is a type of linear classification to predict the categorical data (dependent variable) from a no. of non independent variable
We use Sigmoid Function for this

## Importing Libraries

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the DataSet

In [12]:
dataset = pd.read_csv("Social_Network_Ads.csv")
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

## Diving data into testing and Training set

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)


In [14]:
print(np.concatenate((X_train,Y_train.reshape(len(Y_train),1)),1))

[[    44  39000      0]
 [    32 120000      1]
 [    38  50000      0]
 [    32 135000      1]
 [    52  21000      1]
 [    53 104000      1]
 [    39  42000      0]
 [    38  61000      0]
 [    36  50000      0]
 [    36  63000      0]
 [    35  25000      0]
 [    35  50000      0]
 [    42  73000      1]
 [    47  49000      1]
 [    59  29000      1]
 [    49  65000      0]
 [    45 131000      1]
 [    31  89000      0]
 [    46  82000      0]
 [    47  51000      1]
 [    26  15000      0]
 [    60 102000      1]
 [    38 112000      0]
 [    40 107000      1]
 [    42  53000      0]
 [    35  59000      0]
 [    48  41000      1]
 [    48 134000      1]
 [    38 113000      1]
 [    29 148000      1]
 [    26  15000      0]
 [    60  42000      1]
 [    24  19000      0]
 [    42 149000      1]
 [    46  96000      0]
 [    28  59000      0]
 [    39  96000      1]
 [    28  89000      0]
 [    41  72000      0]
 [    45  26000      1]
 [    33  69000      0]
 [    20  82000 

## Feature Scaling the model

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Logistic Regression of Data

In [16]:
from sklearn.linear_model import LogisticRegression
classifer = LogisticRegression()
classifer.fit(X_train,Y_train)

LogisticRegression()

## Predicting a new Resutlt


In [17]:
print(classifer.predict(sc.transform([[44,39000]])))

[0]


## Predicing Test Set Results

In [18]:
Y_pred = classifer.predict(X_test)
print(np.concatenate((Y_test.reshape(len(Y_test),1),Y_pred.reshape(len(Y_pred),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]]


## Confusion Matrix
The Confusion matrix will show us the exact number of correct predictions and Number of Incorrect predictions. It is a 2D matrix

```
 [ correct 0  incorrect 1]
 [  65            3      ]
 [  8             24     ]
 [ incorrect 0  correct 1]

```

  

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test,Y_pred)
s = accuracy_score(Y_test,Y_pred)
print(f"The confusion matrix is :\n {cm} ")
print(f"The accuracy score is : {s}")


The confusion matrix is :
 [[65  3]
 [ 8 24]] 
The accuracy score is : 0.89


##  Visualizing the Training Set Result

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), Y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifer.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

## Visulaizing the Test set Result

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), Y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifer.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()